created card and form
AnnaApk/my-interviews pull request #3
Opened 2023-12-28 16:00 UTC by AnnaApk

2024-01-06 17:11 UTC, alexbaumgertner commented on src/app/page.module.css
> +.card span {
Лучше не использовать селектор по тегам. Я бы тут сделал элемент у ‘card’

2024-01-06 17:11 UTC, alexbaumgertner commented on src/app/page.module.css
> +.card span {
Хотя похоже, из-за использования UI-библиотеки это не просто сделать.

2024-01-06 17:11 UTC, alexbaumgertner commented on src/app/page.module.css
> +.card span {
<img width="1308" alt="Screenshot 2024-01-06 at 20 09 28" src="https://github.com/AnnaApk/my-interviews/assets/223620/0a24899d-0589-44f5-b9ef-b592a436b984">
Похоже, эти стили вообще не используются. Проверь пожалуйста.

2024-01-06 17:12 UTC, alexbaumgertner commented on src/app/Card.tsx
- [ ] Вынести в @/components

2024-01-06 17:13 UTC, alexbaumgertner commented on src/app/Form.tsx
- [ ] вынести в `@/components`

2024-01-08 14:36 UTC, AnnaApk commented on src/app/page.module.css
> +.card span {
кажется это остались стили "из коробки" 
удалила лишние стили из page.module.css

2024-01-08 14:36 UTC, AnnaApk commented on src/app/Card.tsx
перенесла компоненты в отдельную папку

2024-01-09 06:21 UTC, alexbaumgertner requested changes

2024-01-09 06:21 UTC, alexbaumgertner commented on .vscode/settings.json
> +}
Не хватает пустой строки в конце файла

2024-01-09 06:21 UTC, alexbaumgertner commented on src/app/globals.css
> +  overflow-x: hidden;
Потенциально ошибко-опасное правило, если контент не влезет на страницу — он будет недоступен.

2024-01-09 06:21 UTC, alexbaumgertner commented on src/app/globals.css
> +  text-decoration: none;
Я бы оставил подчеркивание у ссылок.

<blockquote>Убирайте подчёркивание, если планируете стилизовать ссылку как кнопку или другой интерактивный элемент вроде карточки товара. В других случаях лучше его оставить, потому что подчёркивание ссылок привычно для пользователей. Если вы сбросите стили, посетителям сайта будет сложнее отличить ссылки от обычного текста.</blockquote>


https://htmlacademy.ru/blog/css/link-underline

2024-01-09 06:21 UTC, alexbaumgertner commented on src/app/globals.css
> +  text-decoration: none;
Вот еще интересные идеи выделения ссылок https://bureau.ru/soviet/20230126/

2024-01-09 06:21 UTC, alexbaumgertner commented on src/app/page.module.css
> +}
Пустая строка

2024-01-09 06:21 UTC, alexbaumgertner commented on src/components/Form.tsx
> +          id="outlined-required"
id повторяются у всех элементов, судя по


> The id of the input element. 
> Use this prop to make label and helperText
> accessible for screen readers.

должен быть разный

https://mui.com/material-ui/api/text-field/

2024-01-09 06:21 UTC, alexbaumgertner commented on src/components/Form.tsx
> +}
пустая строка

2024-01-09 06:21 UTC, alexbaumgertner commented on src/components/form.module.css
> +}
пустая строка

2024-01-09 11:01 UTC, AnnaApk commented on .vscode/settings.json
> +}
поправила

2024-01-09 11:16 UTC, AnnaApk commented on .vscode/settings.json
> +}
и похоже я создала этот файл, когда правила настройки в VScode, надо привычку вводить смотреть что в коммите делается
добавила его в gitignore

2024-01-09 11:17 UTC, AnnaApk commented on src/app/Form.tsx
перенесла компоненты в отдельную папку

2024-01-09 12:55 UTC, AnnaApk commented on src/app/page.module.css
> +}
добавила

2024-01-09 12:55 UTC, AnnaApk commented on src/components/Form.tsx
> +}
добавила

2024-01-09 12:56 UTC, AnnaApk commented on src/components/form.module.css
> +}
добавила

2024-01-09 12:59 UTC, alexbaumgertner commented on src/app/page.tsx
> +import Card from '../components/Card'
```suggestion
import Card from '@/components/Card'
```

2024-01-09 13:00 UTC, alexbaumgertner commented on src/app/page.module.css
> +}
> добавила

похоже, не докоммитилось или не запушилось — красный кружок остался и если открыть edit file - пустой строки тоже нет.

2024-01-09 13:09 UTC, AnnaApk commented on src/app/page.tsx
> +import Card from '../components/Card'
исправила

2024-01-09 13:19 UTC, AnnaApk commented on src/components/Form.tsx
> +          id="outlined-required"
поправила айдишники

2024-01-09 13:21 UTC, AnnaApk commented on src/app/globals.css
> +  overflow-x: hidden;
Убрала глобальные стили, буду добавлять по необходимости свои тогда

2024-01-09 13:23 UTC, AnnaApk commented on src/app/globals.css
> +  text-decoration: none;
статьи прочитала, спасибо!
как появятся ссылки напишу общие стили для них с учетом рекомендаций/способов из них

2024-01-09 13:51 UTC, alexbaumgertner approved these changes

2024-01-09 15:42 UTC, merged