admin's form to add skill to base
AnnaApk/my-interviews pull request #8
Opened 2024-01-23 16:51 UTC by AnnaApk

2024-01-23 17:27 UTC, AnnaApk commented on migrations/20240123170426_skills-db.ts
> +    table.increments('id');
нужен ли id для skills ? по идее уникальным тут должно быть поле 'skill', можно ли все манипуляции выполнять через него? и при добавлении очередного проверять, чтоб skills не повторялись

2024-01-25 19:18 UTC, alexbaumgertner commented on migrations/20240123170426_skills-db.ts
> +    table.increments('id');
Вот тут хорошие пойнты всегда создавать поле id
https://dba.stackexchange.com/questions/8334/why-should-i-create-an-id-column-when-i-can-use-others-as-key-fields

Я бы добавил еще кейс с переименованием Скилла (например, написанного с ошибкой)


1 - It's faster. A JOIN on an integer is much quicker than a JOIN on a string field or combination of fields. It's more efficient to compare integers than strings.

2 - It's simpler. It's much easier to map relations based on a single numeric field than on a combination of other fields of varying data types.

3 - It's data-independent. If you match on the ID you don't need to worry about the relation changing. If you match on a name, what do you do if their name changes (i.e. marriage)? If you match on an address, what if someone moves?

4 - It's more efficient If you cluster on an (auto incrementing) int field, you reduce fragmentation and reduce overall size of the data set. This also simplifies indexes needed to cover your relations.

2024-01-30 17:51 UTC, AnnaApk commented
промежуточный результат, теперь есть 2 таблицы - вакансии и навыки
навыки можно добавлять в базу и выбирать/добавлять в форме создания вакансии

напишу завтра удаление навыка и редактирование

2024-01-31 20:07 UTC, AnnaApk commented on src/components/EditSkillForm.tsx
> +        />
именно в textarea баг при редактировании - вводится один символ и фокус снимается, курсор пропадает, как поняла дело в перерендере. пока не поняла как поправить

2024-02-02 07:54 UTC, alexbaumgertner commented
Проверю сегодня, если все ок — вольем

2024-02-04 14:58 UTC, alexbaumgertner commented on migrations/20240114140523_init-mgr.ts
> +    table.string('skills');
Такое изменение нарушает принцип миграций, а именно
- единоразовое выполнение каждого изменения (SQL-запроса);

То есть эта миграция, будучи в ветке main уже считается выполненной и больше выполнятся на текущей БД не будет. То есть, поле `skills` будет только при инициализации новой БД.
Миграции, как комммиты — атомарны — в них нельзя добавлять изменения. Любые изменения — только через последующие миграциии

2024-02-04 14:59 UTC, alexbaumgertner commented on migrations/20240114140523_init-mgr.ts
> +    table.string('skills');
Это изменение должно быть в файле migrations/20240123170426_skills-db.ts

2024-02-04 14:59 UTC, alexbaumgertner commented on migrations/20240123170426_skills-db.ts
> +    table.string('skill');
```suggestion
    table.string('skill_name');
```

2024-02-04 15:00 UTC, alexbaumgertner commented on migrations/20240123170426_skills-db.ts
> +    table.string('grade_1');
Думаю, лучше будет так
```suggestion
    table.string('grade_1_desc');
```

2024-02-04 15:20 UTC, alexbaumgertner commented on migrations/20240114140523_init-mgr.ts
> +    table.string('skills');
Еще по формату этого поля — тут должен быть список id скиллов, думаю что все-таки текстом их хранить не удобно, представь 7-10 скиллов будут выглядеть так

```
'2,34,55,12,56,89,21,33,45'
```
- сложно добавлять, редактировать искать по такому полю.

Для связывания вакансий и скиллов нужно сделать отдельную таблицу: `vacancy_skills`

```sql
CREATE TABLE vacancy_skills (
  vacancy_id INTEGER NOT NULL REFERENCES vacancies(vacancy_id),
  skill_id INTEGER NOT NULL REFERENCES skills(skill_id),
  skill_required_level INTEGER CHECK (skill_required_level BETWEEN 1 AND 5),
  PRIMARY KEY (vacancy_id, skill_id)
);
```

пример данных:

## vacancies
|id|title|
|--|-----|
|1 | react developer|
|2 | nextjs developer|
|3 | SRE engineer|


## skills
|id| skill_name (или просто name) | grade_1_desc|
|--|------------------------------|-------------|
|1 | react| уметь сверстать dumb-компонент      |
|2 | nextjs| уметь запустить статичный сайт     |
|3 | HTML| сверстать форму с кнопкой            |

## vacancy_skills
для react разработчик_цы нужно знать HTML И ReactJS

|vacancy_id | skill_id |skill_required_level |
|-----------|----------|---------------------|
|1          | 1        | 3
|1          | 3        | 2

2024-02-04 15:26 UTC, alexbaumgertner commented on src/components/EditSkillForm.tsx
> +          value={inputSkill}
Тут скорее `defaultValue` и тогда это будет uncontrolled component без багов.

https://react.dev/reference/react-dom/components/textarea#providing-an-initial-value-for-a-text-area

2024-02-04 15:26 UTC, alexbaumgertner commented on src/components/EditSkillForm.tsx
> +        />
https://react.dev/reference/react-dom/components/textarea#providing-an-initial-value-for-a-text-area

попробуй default value

2024-02-04 15:27 UTC, alexbaumgertner requested changes
Спасибо за PR!

Посмотри пожалуйста комментарии.

2024-02-05 16:18 UTC, AnnaApk commented on src/components/EditSkillForm.tsx
> +        />
да, так все в порядке, спасибо

2024-02-05 16:29 UTC, AnnaApk commented on migrations/20240114140523_init-mgr.ts
> +    table.string('skills');
то есть столбец skills в первой таблице (вакансий) в принципе лишний? вместо него и будет таблица vacancy_skills?

2024-02-05 16:40 UTC, AnnaApk commented on migrations/20240114140523_init-mgr.ts
> +    table.string('skills');
1. и чтобы это исправить я создам очередной файл миграции, в котором напишу - удалить столбец 

ALTER TABLE vacancies DROP COLUMN skills

2. отдельно еще одну миграцию с созданием третьей таблицы vacancy_skills

3. если нужно переименовать столбцы, допустимо это сделать в одной миграции? 
grade_i в  grade_i_desc

2024-02-05 16:42 UTC, AnnaApk commented on src/components/EditSkillForm.tsx
> +          value={inputSkill}
да, поправила это

2024-02-05 16:58 UTC, AnnaApk commented on migrations/20240114140523_init-mgr.ts
> +    table.string('skills');
в моей форме сейчас можно выбирать несколько уровней одного скила, это не правильно?

2024-02-05 17:58 UTC, alexbaumgertner commented on migrations/20240114140523_init-mgr.ts
> +    table.string('skills');
Да, выбрать можно только один уровень для одного Скилла.

2024-02-05 17:59 UTC, alexbaumgertner commented on migrations/20240114140523_init-mgr.ts
> +    table.string('skills');
> то есть столбец skills в первой таблице (вакансий) в принципе лишний? вместо него и будет таблица vacancy_skills?

Да, так и есть. 
Связь между вакансией и скиллами в related DB — это отдельная таблица.

2024-02-07 14:17 UTC, AnnaApk commented
начала с того, что поправила таблицы ( заголовки пока не трогала) 
разбиралась с селектором от mui , не смогла сделать так, чтоб он принимал в  value массив объектов, поэтому в функции handleSubmitAddCard будет собираться массив объектов по ключам из value.

2024-02-07 15:02 UTC, AnnaApk commented on migrations/20240114140523_init-mgr.ts
> +    table.string('skills');
узнала как вернуть id при создании строки в таблице, теперь можно переписывать функцию добавления новой вакансии

2024-02-08 06:39 UTC, alexbaumgertner commented on migrations/20240114140523_init-mgr.ts
Тк эта миграция уже считается примененной (вмердженной в main ранее, а по Continues Delivery как только код попадает в main-ветку — он деплоится) — в этом файле не должно быть изменений. Их надо перенести в новые миграции.

2024-02-08 06:40 UTC, alexbaumgertner commented on migrations/20240206102143_drop-column-skills.ts
Если изменения в migrations/20240114140523_init-mgr.ts не были влиты в main, то и изменений БД (по идее) не должно было произойти. Эта миграция (по идее) не нужна.

2024-02-08 06:41 UTC, alexbaumgertner commented on migrations/20240206104829_create-table-vacancy-skills.ts
👍

2024-02-08 09:20 UTC, AnnaApk commented on migrations/20240206102143_drop-column-skills.ts
я когда в прошлый раз "экспериментировала" удаляла бд, то есть там сейчас выполнено все этими миграциями, я их выполняла командой 
knex migrate:latest

2024-02-08 11:05 UTC, AnnaApk commented on migrations/20240206102143_drop-column-skills.ts
`import {sql} from '@vercel/postgres';
import { NextResponse } from 'next/server';

interface IEL {
  skillID: number;
  skillLevel: number;
}

export async function POST(request: Request) {
  const requestBody = await request.json();
  const {
    vacancyID,
    reqBody
  } = requestBody

  const values = reqBody.reduce((prev: string, el:IEL, index: number):string => {
    const {skillID, skillLevel} = el;
    let value = '';
    if (index === reqBody.length - 1) {
      value = `(${vacancyID}, ${skillID}, ${skillLevel})`
    } else {
      value = `(${vacancyID}, ${skillID}, ${skillLevel}),\n`
    }
    return (prev + value)
  }, '')

  try {
    await sql`
        INSERT INTO vacancy_skills VALUES
        ${values};`

    return NextResponse.json({}, { status: 200 });
  } catch (error) {
    return NextResponse.json({ error }, { status: 500 });
  }
}
`

пишу запрос на добавление нескольких строк в vacancy_skills и заканчивается ошибкой "error":{"name":"NeonDbError","code":"42601"}, 
"Ошибка NeonDbError с кодом 42601 обычно указывает на синтаксическую ошибку в SQL запросе. "

но при этом если в консоли версель выполнить запрос, подставив строку со значениями полученную и выведенную локально, все выполнилось

2024-02-18 19:27 UTC, alexbaumgertner commented on src/app/api/vacancies/[id]/route.ts
> +      await sql`INSERT INTO vacancy_skills VALUES (${value[0]}, ${value[1]}, ${value[2]});`;
@AnnaApk вот тут ошибка?
Я пытаюсь в Postman запрос сделать
<img width="878" alt="Screenshot 2024-02-18 at 22 26 48" src="https://github.com/AnnaApk/my-interviews/assets/223620/81d7bbfe-f2cb-4468-acc7-9c97e7ed9bab">

2024-02-19 17:17 UTC, AnnaApk commented on src/app/api/vacancies/[id]/route.ts
> +      await sql`INSERT INTO vacancy_skills VALUES (${value[0]}, ${value[1]}, ${value[2]});`;
try {
    for (const value of values) {
      await sql`INSERT INTO vacancy_skills VALUES (${value[0]}, ${value[1]}, ${value[2]});`;

это уже исправленный вариант, так все работает, у версель ограничение оказалось: каждую строку надо записывать отдельно.

2024-02-19 17:30 UTC, AnnaApk commented on src/app/api/vacancies/[id]/route.ts
> +      await sql`INSERT INTO vacancy_skills VALUES (${value[0]}, ${value[1]}, ${value[2]});`;
<img width="1019" alt="image" src="https://github.com/AnnaApk/my-interviews/assets/94643227/ecb4adc0-c089-4bb8-a266-c48657df6380">

залью сейчас последнее, но я только исправила отображение скилов в карточках (там сейчас не хватает пробелов еще)

но ошибки такой нет локально в постмане

2024-02-27 14:51 UTC, alexbaumgertner approved these changes

2024-02-27 14:52 UTC, merged

2024-02-27 14:53 UTC, alexbaumgertner commented
Проверил локально — все работает, круто скиллы добавляются в вакансию!

<img width="777" alt="Screenshot 2024-02-27 at 17 52 47" src="https://github.com/AnnaApk/my-interviews/assets/223620/c7113bd1-c54a-4b49-ad9b-83a47f42747d">
https://dbeaver.io